{"name":"BOOK_dataflow","description":"","version":"1.0","culture":"en-US","modifiedTime":"2023-08-30T08:25:42.330815+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"DIM_DATE":{"queryId":"78fc785f-64c0-4484-ae84-b560541efdc4","queryName":"DIM_DATE","loadEnabled":true},"CUSTOMER_DIM":{"queryId":"1a8ad98d-a41f-46cf-ba7a-1dea73be3702","queryName":"CUSTOMER_DIM","loadEnabled":true},"EMPLOYEE_DIM":{"queryId":"e826182b-daa9-4885-9da7-b44e73e43f00","queryName":"EMPLOYEE_DIM","loadEnabled":true},"PRODUCT_DIM":{"queryId":"d4faf5f5-a827-45e2-af44-9d9e10d40d1a","queryName":"PRODUCT_DIM","loadEnabled":true},"ORDER_FACT":{"queryId":"0d22975a-3ae3-4961-8bb6-ac0515a2d555","queryName":"ORDER_FACT","loadEnabled":true}},"document":"section Section1;\r\nshared DIM_DATE = let\r\n  Source = Excel.Workbook(Web.Contents(\"https://uithcm-my.sharepoint.com/personal/18520629_ms_uit_edu_vn/Documents/Ứng dụng/Microsoft Power Query/Uploaded Files/dwh.xlsx\"), null, true),\r\n  #\"Navigation 1\" = Source{[Item = \"DIM_DATE\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"DATE_KEY\", type text}, {\"DATE\", type date}, {\"MONTH\", Int64.Type}, {\"YEAR\", Int64.Type}, {\"MONTH_NAME\", type text}}, \"en\")\r\nin\r\n  #\"Changed column type\";\r\nshared CUSTOMER_DIM = let\r\n  Source = Excel.Workbook(Web.Contents(\"https://uithcm-my.sharepoint.com/personal/18520629_ms_uit_edu_vn/Documents/Ứng dụng/Microsoft Power Query/Uploaded Files/dwh.xlsx\"), null, true),\r\n  #\"Navigation 1\" = Source{[Item = \"CUSTOMER_DIM\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CUSTOMER_ID\", type text}, {\"NAME\", type text}, {\"TYPE\", type text}, {\"GENDER\", type text}, {\"PROVINCE_CODE\", type text}, {\"MIEN\", type text}}, \"en\")\r\nin\r\n  #\"Changed column type\";\r\nshared EMPLOYEE_DIM = let\r\n  Source = Excel.Workbook(Web.Contents(\"https://uithcm-my.sharepoint.com/personal/18520629_ms_uit_edu_vn/Documents/Ứng dụng/Microsoft Power Query/Uploaded Files/dwh.xlsx\"), null, true),\r\n  #\"Navigation 1\" = Source{[Item = \"EMPLOYEE_DIM\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"EMPLOYEE_ID\", type text}, {\"NAME\", type text}, {\"TYPE\", type text}, {\"GENDER\", type text}, {\"COMPANY\", type text}}, \"en\")\r\nin\r\n  #\"Changed column type\";\r\nshared PRODUCT_DIM = let\r\n  Source = Excel.Workbook(Web.Contents(\"https://uithcm-my.sharepoint.com/personal/18520629_ms_uit_edu_vn/Documents/Ứng dụng/Microsoft Power Query/Uploaded Files/dwh.xlsx\"), null, true),\r\n  #\"Navigation 1\" = Source{[Item = \"PRODUCT_DIM\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"PRODUCT_ID\", type text}, {\"SKU\", type text}, {\"TYPE\", type text}, {\"NAME\", type text}, {\"RATING_AVERAGE\", type number}, {\"PRICE\", Int64.Type}}, \"en\")\r\nin\r\n  #\"Changed column type\";\r\nshared ORDER_FACT = let\r\n  Source = Excel.Workbook(Web.Contents(\"https://uithcm-my.sharepoint.com/personal/18520629_ms_uit_edu_vn/Documents/Ứng dụng/Microsoft Power Query/Uploaded Files/dwh.xlsx\"), null, true),\r\n  #\"Navigation 1\" = Source{[Item = \"ORDER_FACT\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"ORDER_NUMBER\", type text}, {\"CUSTOMER_ID\", type text}, {\"PRODUCT_ID\", type text}, {\"EMPLOYEE_ID\", type text}, {\"DATE\", type date}, {\"QUANTITY\", Int64.Type}, {\"SKU\", type text}, {\"PRODUCT_TYPE\", type text}, {\"PRODUCT_NAME\", type text}, {\"PRICE\", Int64.Type}, {\"DATE_KEY\", type text}}, \"en\")\r\nin\r\n  #\"Changed column type\";\r\n","connectionOverrides":[{"path":"https://uithcm-my.sharepoint.com/personal/18520629_ms_uit_edu_vn/Documents/Ứng dụng/Microsoft Power Query/Uploaded Files/dwh.xlsx","kind":"Web","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Web\",\"path\":\"https://uithcm-my.sharepoint.com/personal/18520629_ms_uit_edu_vn/Documents/%E1%BB%A8ng%20d%E1%BB%A5ng/Microsoft%20Power%20Query/Uploaded%20Files/dwh.xlsx\"}","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"DIM_DATE","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DIM_DATE.csv"},"attributes":[{"name":"DATE_KEY","dataType":"string"},{"name":"DATE","dataType":"date"},{"name":"MONTH","dataType":"int64"},{"name":"YEAR","dataType":"int64"},{"name":"MONTH_NAME","dataType":"string"}]},{"$type":"LocalEntity","name":"CUSTOMER_DIM","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUSTOMER_DIM.csv"},"attributes":[{"name":"CUSTOMER_ID","dataType":"string"},{"name":"NAME","dataType":"string"},{"name":"TYPE","dataType":"string"},{"name":"GENDER","dataType":"string"},{"name":"PROVINCE_CODE","dataType":"string"},{"name":"MIEN","dataType":"string"}]},{"$type":"LocalEntity","name":"EMPLOYEE_DIM","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"EMPLOYEE_DIM.csv"},"attributes":[{"name":"EMPLOYEE_ID","dataType":"string"},{"name":"NAME","dataType":"string"},{"name":"TYPE","dataType":"string"},{"name":"GENDER","dataType":"string"},{"name":"COMPANY","dataType":"string"}]},{"$type":"LocalEntity","name":"PRODUCT_DIM","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"PRODUCT_DIM.csv"},"attributes":[{"name":"PRODUCT_ID","dataType":"string"},{"name":"SKU","dataType":"string"},{"name":"TYPE","dataType":"string"},{"name":"NAME","dataType":"string"},{"name":"RATING_AVERAGE","dataType":"double"},{"name":"PRICE","dataType":"int64"}]},{"$type":"LocalEntity","name":"ORDER_FACT","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ORDER_FACT.csv"},"attributes":[{"name":"ORDER_NUMBER","dataType":"string"},{"name":"CUSTOMER_ID","dataType":"string"},{"name":"PRODUCT_ID","dataType":"string"},{"name":"EMPLOYEE_ID","dataType":"string"},{"name":"DATE","dataType":"date"},{"name":"QUANTITY","dataType":"int64"},{"name":"SKU","dataType":"string"},{"name":"PRODUCT_TYPE","dataType":"string"},{"name":"PRODUCT_NAME","dataType":"string"},{"name":"PRICE","dataType":"int64"},{"name":"DATE_KEY","dataType":"string"}]}]}